### ISSUE TITLE
URL with dash in it

### ISSUE THREAD

**Issue by k0rtina** [pierrecoll/autoprox#2]
autoprox throws an error that it cant find the URL... when you supply a URL that contains a dash/hyphen

**Fail:**  Invalid argument: Url missing
autoprox.exe -u:https://azuretenant-admin.sharepoint.com -p:proxy.pac

**Working:**
autoprox.exe -u:https://azuretenantadmin.sharepoint.com -p:proxy.pac
autoprox.exe -u:https://azuretenant.admin.sharepoint.com -p:proxy.pac

Is there some sort of way that I need to encode the URL?

**Comment by jerome42** [comment]
Hello,
i encountered the same issue with URL https://www.credit-agricole.fr
whith version 2.44 of Autoprox

I think this issue is specific with "-a", not "-"

I bypassed this issue by replacing the '-' by %2D, it seems to work but a module correction is welcome

**Comment by pierrecoll** [comment]
Should be fixed with version 2.45
