### ISSUE TITLE
Server 2022

### ISSUE THREAD

**Issue by SteMan1066** [pierrecoll/autoprox#3]
Hi. I'm coming across issue running this on Server 2022. Is there a workaround?? Works fine on server 2016

PS C:\Users\auser\Desktop\Autoprox> .\autoprox.exe -o -u:https://www.microsoft.com/ -p:
C:\Users\auser\Desktop\Autoprox\WPAD.dat
Searching proxy for url : https://www.microsoft.com/
Searching proxy using file : C:\Users\auser\Desktop\Autoprox\WPAD.dat
The Winsock 2.2 dll was found okay
Calling InternetInitializeAutoProxyDll with C:\Users\auser\Desktop\Autoprox\WPAD.dat and using helper functions

  ERROR: InternetInitializeAutoProxyDll failed with error number 0x0 0.

(0) (0x0) The operation completed successfully.

**Comment by nmoinvaz** [comment]
I think you have to copy the older version of jsproxy.dll in the same directory as the executable because InternetInitializeAutoProxyDll is no longer supported on newer versions of Windows.

**Comment by SteMan1066** [comment]
great, thank you. It now works a treat :-)

**Comment by pierrecoll** [comment]
FYI, this was fixed in latest version 2.47 3 years ago!

https://github.com/pierrecoll/autoprox/commit/82a3afba9d3b594bf03b01f99c41db9a3eeda508

Handling issue with Windows11 where JSproxy.dll functions all return …
…FALSE: loading legacy Windows10 Jsproxy.dll instead a a dirty workaround
