### ISSUE TITLE
Invalid Link in MS Docs

### ISSUE THREAD

**Issue by nixtar** [pierrecoll/autoprox#4]
Hey, looks like a URI for this app in the MS docs has an outdated/invalid link.

https://learn.microsoft.com/en-us/troubleshoot/developer/browsers/connectivity-navigation/optimize-pac-performance#testing-with-autoproxexe

Points to https://emeaie.azurewebsites.net/pierrelc/autoprox.zip and this currently returns a 404 with body of `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`.

**Comment by pierrecoll** [comment]
Hi,
Yes, sorry, 
[autoprox.zip](https://github.com/user-attachments/files/16026210/autoprox.zip)
I retired from Microsoft in Mai and this url isn't available anymore. I have attached a zip file with the tool.
BR
Pierre-Louis

**Comment by nixtar** [comment]
No worries mate, thanks for your work on these various tools over the years. ❤️
